import time 
def collegeapps():
    print ("The sky was beginning to darken as you make your way towards a local starbucks to meet with your friend.")
    time.sleep(2)
    print ("Both of you decided to open all of your college acceptance and rejection letters together. Today was the day where the last of the remaining applications was processed.")
    time.sleep(3)
    print ('You decide to get a drink before your friend arrives')
    time.sleep(3)
    import random
    option_list = ['Iced Coffee with Almond Milk!','Mango Dragonfruit Refresher!','Caffe Americano!']
    print(random.choice(option_list))
    time.sleep(2)
    print('Good choice!')
    print('Once you scower the premise for two available seats you finally find one with a good window seat, excited you run over and sit down and look through your bag.')
    time.sleep(5)
    for sit in [' take out your Macbook pro','take a deep breath','take a long sip of your drink']:
        print('Then you' +sit+'.')
    time.sleep(4)
    print ("A few minutes after you arrive, you see your friend dash over to you anxiously. She pulls out her laptop and asks you to open your first letter.")
    choice=raw_input('Will you open it first?(Yes/No)')
    while choice != 'Yes' and choice !='No':
        choice=raw_input('Invalid Answer. Try again(Yes/No)')
    if choice == 'Yes':
        print('After much hesitation, you open the letter. Congratulations! You were accepted.')
        print('You look to your friend for her response')
        time.sleep(3)
        print ("...")
        time.sleep(3)
        print ("..")
        time.sleep(2)
        print (".")
        time.sleep(4)
        print('"I was rejected. "')
    if choice == 'No':
        print('You insist that she opens it first. She obliges, and her wide smile instantly disappears.')
        time.sleep(3)
        print ("...")
        time.sleep(3)
        print ("..")
        time.sleep(2)
        print (".")
        time.sleep(4)
        print('"I was rejected. "')
    time.sleep(3)
    print ('In the corner of your eye, you see your friends eyes begin to tear up')
    time.sleep(3)
    print ('After five or so times of opening letters, the color drains from her eyes')
    choice=raw_input('What will you do?(Let her cry it out/Give her a big boy talk)')
    while choice != 'Let her cry it out' and choice !='Give her a big boy talk':
        choice=raw_input('Invalid Answer. Try again(Let her cry it out/Give her a big boy talk)')
    if choice == 'Let her cry it out':
        print('Your friend runs out in embarassment and ignores you in hopes that you will not talk about her shame.')
        time.sleep(3)
        print('Even if you got into your dream school, you lost a friend in the process')
        time.sleep(3)
        print('     __')
        print('  _ / /')
        print(' (_) | ')
        print('   | | ')
        print('  _| | ')
        print(' (_) | ')
        print('    \_\ ')
        return
    else: #Give her a bog boy talk
            print('You take a deep breath.')
    time.sleep(3)
    print('"Look dear friend of mine."')
    time.sleep(2)
    print('You then proceed to read her the entire script of the bee movie.')
    time.sleep(2)
    print('She cries.')
    time.sleep(3)
    print('On lookers stare and they also proceed to cry.')
    time.sleep(2)
    print('By the time you finish, your friend has fully changed into a resposible human. Humans have stopped sinning, the world is calm. You get a standing ovation.')
    time.sleep(2)
    print('Your friend agrees to go to community college and you both are friends until the end of eternity')
       
